version: "3.8"


services: 
    groi-api:
        container_name: backend
        build: ./
        working_dir: /usr/src/groi-api
        environment: 
            REDIS_URI: redis://redis:6379
        links: 
            - redis
        ports: 
            - "3001:3001"
    
    # Redis
    redis:
        image: redis:latest
        ports:
            - "6379:6379"